extends: airbnb
parser: babel-eslint
plugins:
  - react
  - jsx-a11y
  - import
rules:
  semi:
    - 1
    - never
  arrow-parens:
    - 2
    - as-needed
    - requireForBlockBody: false
  no-confusing-arrow:
    - 0
  react/prop-types:
    - 1
    - skipUndeclared: true
env:
  browser: true
